extern doublereal d1mach_(integer *i__);
extern integer i1mach_(integer *i__);
extern E_f r1mach_(integer *i__);
extern integer imdcon_(integer *k);
extern doublereal rmdcon_(integer *k);
extern int sumsl_(integer *n, doublereal *d__, doublereal *x, S_fp calcf, S_fp calcg, integer *iv, integer *liv, integer *lv, doublereal *v, integer *uiparm, doublereal *urparm, U_fp ufparm);
extern int smsno_(integer *n, doublereal *d__, doublereal *x, S_fp calcf, integer *iv, integer *liv, integer *lv, doublereal *v, integer *uiparm, doublereal *urparm, U_fp ufparm);
extern int sumit_(doublereal *d__, doublereal *fx, doublereal *g, integer *iv, integer *liv, integer *lv, integer *n, doublereal *v, doublereal *x);
extern int snoit_(doublereal *d__, doublereal *fx, integer *iv, integer *liv, integer *lv, integer *n, doublereal *v, doublereal *x);
extern int dbdog_(doublereal *dig, integer *lv, integer *n, doublereal *nwtstp, doublereal *step, doublereal *v);
extern int ltvmul_(integer *n, doublereal *x, doublereal *l, doublereal *y);
extern int lupdat_(doublereal *beta, doublereal *gamma, doublereal *l, doublereal *lambda, doublereal *lplus, integer *n, doublereal *w, doublereal *z__);
extern int lvmul_(integer *n, doublereal *x, doublereal *l, doublereal *y);
extern int sgrad2_(doublereal *alpha, doublereal *d__, doublereal *eta0, doublereal *fx, doublereal *g, integer *irc, integer *n, doublereal *w, doublereal *x);
extern int vvmulp_(integer *n, doublereal *x, doublereal *y, doublereal *z__, integer *k);
extern int wzbfgs_(doublereal *l, integer *n, doublereal *s, doublereal *w, doublereal *y, doublereal *z__);
extern int assst_(integer *iv, integer *liv, integer *lv, doublereal *v);
extern int deflt_(integer *alg, integer *iv, integer *liv, integer *lv, doublereal *v);
extern doublereal dotprd_(integer *p, doublereal *x, doublereal *y);
extern int itsum_(doublereal *d__, doublereal *g, integer *iv, integer *liv, integer *lv, integer *p, doublereal *v, doublereal *x);
extern int litvmu_(integer *n, doublereal *x, doublereal *l, doublereal *y);
extern int livmul_(integer *n, doublereal *x, doublereal *l, doublereal *y);
extern int parck_(integer *alg, doublereal *d__, integer *iv, integer *liv, integer *lv, integer *n, doublereal *v);
extern doublereal reldst_(integer *p, doublereal *d__, doublereal *x, doublereal *x0);
extern logical stopx_(integer *idummy);
extern int vaxpy_(integer *p, doublereal *w, doublereal *a, doublereal *x, doublereal *y);
extern int vcopy_(integer *p, doublereal *y, doublereal *x);
extern int vdflt_(integer *alg, integer *lv, doublereal *v);
extern int vscopy_(integer *p, doublereal *y, doublereal *s);
extern doublereal v2norm_(integer *p, doublereal *x);
extern int humsl_(integer *n, doublereal *d__, doublereal *x, S_fp calcf, S_fp calcgh, integer *iv, integer *liv, integer *lv, doublereal *v, integer *uiparm, doublereal *urparm, U_fp ufparm);
extern int humit_(doublereal *d__, doublereal *fx, doublereal *g, doublereal *h__, integer *iv, integer *lh, integer *liv, integer *lv, integer *n, doublereal *v, doublereal *x);
extern int dupdu_(doublereal *d__, doublereal *hdiag, integer *iv, integer *liv, integer *lv, integer *n, doublereal *v);
extern int gqtst_(doublereal *d__, doublereal *dig, doublereal *dihdi, integer *ka, doublereal *l, integer *p, doublereal *step, doublereal *v, doublereal *w);
extern int lsqrt_(integer *n1, integer *n, doublereal *l, doublereal *a, integer *irc);
extern doublereal lsvmin_(integer *p, doublereal *l, doublereal *x, doublereal *y);
extern int slvmul_(integer *p, doublereal *y, doublereal *s, doublereal *x);
